name: Deploy to static server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to static server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      - name: upload files
        uses: fangbinwei/aliyun-oss-website-action@v1.4.0
        with:
            accessKeyId: ${{ secrets.ACCESSKEY_ID }}
            accessKeySecret: ${{ secrets.ACCESSKEY_SECRET }}
            bucket: web-toiletmc
            endpoint: oss-cn-hangzhou.aliyuncs.com
            folder: ./build
